# Discussion and Conclusion {#discussionandconclusion}

We achieve stationarity by a -- to our knowledge -- not yet described transformation in the literature with very satisfying results on our dataset. Our results support the assumption that a transformed tree ring time series can be reasonalbly described by an ARMA(1,1) process. Furthermore, we show that an ARMA(1,1) process can also be helpful to impute missing data. In particular, we give some evidence that the approach based on an ARMA(1,1) process outperfoms simple linear interpolation on the original time series.

In our analysis, the shape of the trend, which we use to achieve stationarity, is not explained by exogenous variables. However, the growth of trees is likely influenced by many factors as for example the climate, soil, slope, exposition, forest cultivation, sun activity (e.g. 11-year cycle) and others. In case the exogoneous variables are known at a specific time, but tree ring data are missing, the knowledge of such relationships might be helpful to improve the imputations. A preliminary analysis based on an ARMA model with exogeneous variables^[Such models are also called ARMAX.] from the U.S. National Oceanographic and Athmosperic Administration (NOAA) for Arizona and Arizonian tree ring data from R-package `dplr` has shown the potential usefulness of such an approach. An unsolvable problem is however the very limited data availability since climatic data were not (systematically) collected before 1895.
