---
title: "Dendrochronologies: Dating wooden artifacts"
author: "Time Series Analysis"
date: '`r Sys.Date()`'
bibliography: final_project.bib
output:
    pdf_document:
        toc: no
        fig_caption: yes
        fig_height: 6
        fig_width: 7
        includes:
            in_header: latex/mystyles.sty
            before_body: latex/before_body.tex
        keep_tex: yes
        latex_engine: xelatex
        number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(error=TRUE,
                      warning=FALSE,
                      message=FALSE,
                      echo=FALSE,
                      cache=FALSE,
                      dpi=300,
                      fig.width=7, # Default figure widths
                      fig.asp=0.618,
                      fig.align="center",
                      fig.path = "./figures/",
                      out.width = "0.7\\linewidth")
knitr::opts_knit$set(eval.after='fig.cap')
```

# Abstract
words words words

# Introduction

Dendrochronology is an archaeological method used for dating artifacts. Chronologies are constructed by measuring the patterns of tree ring widths from individual wooden artifacts, then overlaying the data to build up a continuous series of mean yearly ring widths spanning hundreds to thousands of years. Chronologies are generally constructed for defined geographical regions as the environment (i.e the local climate, soil properties and terrain) has substantial impact on the growth of trees.

Newly measured artifacts are matched to existing, dated chronologies serving the double purpose of strengthening the chronology and dating the artifact in question.

## Timeseries used

The chronology used for this project has been compiled from individual measurements of buildings in the Bernese Oberland which are all located above 900 meters. Typically, the wooden structure of old buildings is sampled by boring the beams. The drilling core is then analyzed by microscoping, recording the sequence of tree ring widths. Spruce was a common building material and there is a wealth of houses supplying data. The data can be assumed to originate almost entirely from trees that grew above 900 meters since trees were rarely transported uphill. The data has been supplied by the archaeological service of the canton Berne [@dendroBern] through a personal contact at the dendrology laboratory in Sutz, BE.

## Timeseries analysis applied to dendrochronologies

- WOOLLONS: Usually ARMA1,1 / AR1 processes

- dplR: AR2

- We will look at AR1, ARMA1,1 more closely

# Methods

## Data
The chronology spans the years from 1332 to 2017 (685 years). The supplier of the data recommended to ignore data after 1800 due to an insufficient amount of data for these years.

The predictor represents the yearly mean tree ring width of all the individual measurements with data for a given year. The unit is `mm`.


## Fitting -> David

## imputing strategies -> Florian

    - imputeTS: na.kalman -> emphasize this
    
    - forecast: na.interp
    
    - zoo: na.approx
    
## Use of exogeneous data


# Results & Discussion

## Data -> David

- Transformation, model fitting 



## Imputation -> Florian

- Introduce missing values

- imputation using different strategies

- discussion of imputation results

# Conclusion

To be seen

# References

