# Methods

The dataset used as well as the methods employed are detailed.

## Data
The dataset ${rwl}$ comprises measurements of $N=234$ tree ring sequences originating from the Bernese Oberland. The individual sequences are dated (the most recent ring has a year associated to it), which allows to give the timespan from oldest tree (first ring measured )to most recent tree as 1332 to 2017. The length of the series is therefore $T=686$ years.

Let $R_t$ the set ${r_{ti}, i=1,...N}$ of ring width measurements for fixed year $t, t \in [1332,2017]$.

Let $n_t = |R_t| = \sum^N_{i=1} \mathds{1}{y_{ti} \neq NA}$, the cardinality for a fixed year $t$, also denoted the *sample depth*.

Let $\bar{r_t} = \frac{1}{n_t}\sum^N_{i=1}r_{ti}*\mathds{1}{r_i \neq NA}$, the mean ring width for a fixed year $t$.

Let ${sd}_t = \sqrt{\frac{1}{n_t-1}\sum^N_{i=1}(y_i-x_t)^2*\mathds{1}{y_i \neq NA}}$, the sample standard deviation for year $t$.

Let $\{\bar{r_t}, t=1,...,T\}$ the set of yearly mean tree ring widths of all the individual trees with data for a given year. The unit is `1/100 mm`.

```{r datacharacteristics, fig.cap="Cardinality (left), mean ring width (center) and SD (right) per year", out.width = "\\linewidth"}
par(mfrow=c(1,3))
plot(rwl_depth~time,type="l",xlab="Year",ylab="Sample depth [#]")
plot(rwl_mean~time,type="l" ,xlab="Year",ylab="Mean ringwidth [1/100 mm]")
plot(rwl_sd~time,type="l",xlab="Year",ylab="SD [1/100 mm]")
par(op)
```

The supplier of the data recommended to ignore data after 1800 due to insufficient quality of data for these years, with a prevalence of young trees distorting $\bar{r_t}$ in that time range. Additionally, it was decided to discard data before 1400 because of a very small sample depth in years before 1400. The analysis has therefore been conducted with the set ${r_t, t \in [1400;1800]}$.

## Stationarity of the time series

In the following section, removal of trend and model fitting will be discussed. As seen in [fig:datacharacteristics], there is no apparent seasonal component present in the data.

### Removing trend

Several approaches were studied to deal with heteroskedasticity and trend removal. These approaches wil be presented and discussed here.

Overview of the methods considered:

1. **Woollons** Described in [@woollons1990time]. The proposed approach is an estimate of the form $Y = alpha*t^(beta)*exp(delta*t)$. Taking the log on both sides yields something linear in $ln(t)$
2. **Power tranformation of residuals**
3. **Box-Cox transform** Tranformation that yields a normally distributed timeseries
4. **Log transformation, polynomials**

## imputing strategies -> Florian

    - imputeTS: na.kalman -> emphasize this

    - forecast: na.interp

    - zoo: na.approx

## Use of exogeneous data

