---
title: "Proposal"
author: "Time Series Analysis"
date: "8 März 2018"
bibliography: ../final_project.bib
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Dataset

Dendrochronology data has been supplied by the archaeological department of the canton Berne [@dendroBern].

## Analysis
```{r preparedata, echo=FALSE}
# Reading in the spruce data for altitudes below 900 m
spruce_sub900 <- read.table("../data/62163_picea_sub900.txt",
                                      skip=4,nrows=89)
spruce_sub900_lastrow <- read.table("../data/62163_picea_sub900.txt",
                                              skip=94,nrows=1)
ss9 <- spruce_sub900[,-c(1,2,3)]
ss9l <- spruce_sub900_lastrow[,-c(1,2,3)]

# Some preliminary analyses
library(itsmr)
series <- c()
for (i in 1:nrow(ss9)) {
    for(j in 1:ncol(ss9)){
        series <- c(series,as.integer(ss9[i,j]))
    }
}
series <- c(series,as.integer(ss9l))

spruce_sub900_ts <- ts(series,end=2017)
t <- seq(from=1,length=length(series))
t_sq <- t^2
t_cu <- t^3
```

```{r analysisresults}
plot(spruce_sub900_ts,
     main="Spruce, < 900 m",
     ylab="tree ring width [1/100 mm]",
     xlab="year")

model <- lm(spruce_sub900_ts~t)
summary(model) # cubic trend is still significant

resid_spruce_sub900 <- residuals(model)
resid_spruce_sub900_ts <- ts(resid_spruce_sub900,end=2017)
mean(resid_spruce_sub900_ts) # ~ zero mean
qqnorm(resid_spruce_sub900_ts) # close to a normal distribution
hist(resid_spruce_sub900_ts) # slightly right-skewed

plotc(resid_spruce_sub900_ts)

acf(resid_spruce_sub900_ts,lag.max = 200)
# Sample ACF shows no indication of iid-ness

Box.test(resid_spruce_sub900_ts,lag=200,type="Ljung-Box")
# Reject H0: The residuals are not iid
```

# Questions to be answered

Climatic trends are to be identified by analyzing the correlation between 3 different chronologies.

# Methods

The project team will answer the questions using the following methods:

* Method 1
* Method 2


# References
